### ISSUE TITLE
Redirect URL  

### ISSUE THREAD

**Issue by kiranmaya** [zerodhatech/dotnetkiteconnect#13]
Im writing c# trading application ,do i require to host redirect page in any webserver?
is there any sample php file for redirection ?

**Comment by kiranmaya** [comment]
after i searched a lot ,phython users redirecting locally to http://127.0.0.1:19291/kite-redirect , is c# client will listen to https requests at 192191 port ?
or do i have to catch request token in my webserver ,store it to a file ,read it back to app again.

**Comment by ajinasokan** [comment]
You can create a localhost server and use it as redirect url instead of using a webserver

**Comment by kiranmaya** [comment]
for those ,who need storing key and retrieving
```
<?php

$text = htmlspecialchars($_GET["text"]);

$fh = fopen("key.txt", 'w') or die("can't open file");  
$textToWrite =  $text ; 
fwrite($fh, $textToWrite);
fclose($fh);
echo $text;
?>
```
`<?php

header('Content-Type: text/plain');

 echo ( file_get_contents('key.txt') );
  

?>`
