### ISSUE TITLE
Not Compatible with .net core

### ISSUE THREAD

**Issue by ssijbabu** [zerodhatech/dotnetkiteconnect#14]
Hi Team,
Requesting you to change the code as per .NET Standard, so that it will be compatible with both .net framework and .net core.

Please find an alternative for the below two library.
System.Web.Script.Serialization;
Microsoft.VisualBasic.FileIO;

Regards
Sujay Babu

**Comment by ajinasokan** [comment]
We have plans to port it to .Net core. But we can't give an ETA at the moment. Because our existing clients are on .Net standard. This will be probably a part of the next major release.

**Comment by Anu666** [comment]
Any idea when this porting to .NET Core would be complete ?
