### ISSUE TITLE
Unable to get Quote Change value

### ISSUE THREAD

**Issue by ShlokC** [zerodhatech/dotnetkiteconnect#2]
Could you update the GetQuote() to return change and change_percent? current GetQuote() method returns Change = data["net_change"] 

As per kite3 documentation 
net_change(float) | The absolute change from yesterday's close to last traded price

change(float) | Absolute change from the last traded price to last close price

or could you confirm that these values are same?

**Comment by ajinasokan** [comment]
We have removed change percentage from kite3 APIs. That was a mistake in the docs. We will fix that. FYI, change percentage can be calculated from net_change.

**Comment by ShlokC** [comment]
could you confirm that the values of net_change and change are same?

**Comment by ajinasokan** [comment]
Yes, they are.
