### ISSUE TITLE
Compatibility with .NET Core ??

### ISSUE THREAD

**Issue by Anu666** [zerodhatech/dotnetkiteconnect#24]
The documentation mentions that the package is compatible with Framework 4.5.

Just wanted to know if the package can be used with the latest .NET Core 3.1 version as the Framework is being depreciated and the future is .NET Core.

**Comment by ajinasokan** [comment]
We will be porting library to .Net standard. So it will be compatible with .Net Core and .Net framework at the same time. Work for port will start as early as next week.

**Comment by harishrathi** [comment]
Any date by when this will be done?

**Comment by ajinasokan** [comment]
This issue is being tracked in #25
