### ISSUE TITLE
Migration to .Net Standard

### ISSUE THREAD

**Issue by ajinasokan** [zerodhatech/dotnetkiteconnect#25]
This issue is to track the library migration to .Net Standard target.
This will allow devs to use library cross platform and in both .Net Core and .Net Framework projects.

**Comment by ajinasokan** [comment]
Here is an early version: https://github.com/zerodhatech/dotnetkiteconnect/tree/netstandard

Tested only in Linux at the moment. Will release once tests are fine in macOS and Windows.

**Comment by harishrathi** [comment]
Is it released?

**Comment by ajinasokan** [comment]
Not yet. Waiting for #27 to merge.

**Comment by blueelvis** [comment]
@ajinasokan - Is it possible to move it to .Net Core 3.1 LTS or .Net Core 2.1 LTS since .Net Core 2.0 is [EOL](https://dotnet.microsoft.com/download/dotnet-core)?

**Comment by ajinasokan** [comment]
@blueelvis Library is targeting netstandard20. It should be compatible with .Net Core 2.0+ and .Net Framework 4.6.1+. More info [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support). We didn't want to support only .Net Core because most of our users are on .Net Framework.

**Comment by ajinasokan** [comment]
An alpha build is available in [releases](https://github.com/zerodhatech/dotnetkiteconnect/releases/tag/v3.0.5-alpha). You can either use the DLL file or the nuget package. You can add this to your .Net Core and .Net Framework projects.

**Comment by blueelvis** [comment]
Sure. Thanks! I will check it out shortly and let you know how it works.

**Comment by ajinasokan** [comment]
This has been merged in #28
