### ISSUE TITLE
.net core 3.1 compatability

### ISSUE THREAD

**Issue by prashanthganathe** [zerodhatech/dotnetkiteconnect#26]
Hi,
with .net core, getting this error.

System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.'

Any possible solution?

**Comment by ajinasokan** [comment]
This library doesn't depend on "System.Web.Extensions". It has to be from the references you added or your project itself.
