### ISSUE TITLE
How to RenewAccessToken using refresh token?

### ISSUE THREAD

**Issue by sai-manoj-kumar** [zerodhatech/dotnetkiteconnect#3]
The initial RefreshToken that we get from User object is an empty string. So, it is not working while calling RenewAccessToken() to renew the access token. Is there any sample code which shows how to use it correctly?

**Comment by ajinasokan** [comment]
Check out [this thread](https://kite.trade/forum/discussion/3203/renew-access-token-what-is-the-use)

**Comment by sai-manoj-kumar** [comment]
@ajinasokan Thanks for the link. Also, what is the time to expire of the access token after it is issued?

**Comment by ajinasokan** [comment]
AccessToken expires every day morning and also when you log out.
