### ISSUE TITLE
Request to update Readme...

### ISSUE THREAD

**Issue by NavjotSinghMinhas** [zerodhatech/dotnetkiteconnect#4]
Hi,

The library available is not compatible with .net 4.5, please update it to c# 7 i.e 4.7 for rebuild purposes.

Thanks

**Comment by ajinasokan** [comment]
At the moment we don't have any plans to port it because we have a few legacy systems depending on this. Can you elaborate on your use case? If it is just for using it with your project then I would recommend using the NuGet package instead of adding this project to your solution.
