### ISSUE TITLE
 Captcha of cloudflare is returning in api instead of the data - KiteConnect

### ISSUE THREAD

**Issue by AshishInnovantes** [zerodhatech/dotnetkiteconnect#5]
Captcha of Cloudflare is returning in API instead of the data and throws exception below.
Unexpected content type text/html; charset=UTF-8 <!DOCTYPE html>

at var usr = kites.GenerateSession(req_token, MyAPISecret);

Also, I have attached the complete error it's returning 

Please help what to do?
[error.txt](https://github.com/zerodhatech/dotnetkiteconnect/files/2218866/error.txt)

**Comment by ajinasokan** [comment]
Looks like Cloudflare is detecting your API call as bot traffic. We'll fix it. You can post further questions in our [forum](https://kite.trade/forum/) for quicker response.
