### ISSUE TITLE
Issue with subscribing to LTP

### ISSUE THREAD

**Issue by rsiddhartht** [zerodhatech/dotnetkiteconnect#9]
Hello,

I believe this might be an issue, w.r.t the way we subscribes to ticks, for an instrument. I am interested in getting the LTP for an instrument and following is the code to achieve the same:

```
var testToken = new uint[]
{
13406210
};
_ticker.Subscribe(Tokens: testToken);
_ticker.SetMode(Tokens: testToken, Mode: Constants.MODE_LTP);
```

Even though the mode specified is LTP, the OnTick() method is called every second with the same LTP value (please check the issue raised in Kite forum: [Kite Forum Link](https://kite.trade/forum/discussion/5326/ticker-behavior-confirmation#latest)).

Can you please have a look into this?

Thanks!

**Comment by ajinasokan** [comment]
Closing this issue in favor of the discussion in the forum.
